ALTER TABLE reservations
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE reservation_documents
    ALTER COLUMN uploaded_at TYPE TIMESTAMPTZ USING uploaded_at AT TIME ZONE 'UTC',
    ALTER COLUMN uploaded_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE import_previews
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE import_logs
    ALTER COLUMN imported_at TYPE TIMESTAMPTZ USING imported_at AT TIME ZONE 'UTC',
    ALTER COLUMN imported_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE schema_migrations
    ALTER COLUMN applied_at TYPE TIMESTAMPTZ USING applied_at AT TIME ZONE 'UTC',
    ALTER COLUMN applied_at SET DEFAULT CURRENT_TIMESTAMP;
